# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/rinu2/Documents/Kichi@git/RedPitaya-FPGA/prj/Examples/Frequency_counter/tmp/freq/freq.srcs/sources_1/bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
# IP: The module: 'system_util_ds_buf_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rinu2/Documents/Kichi@git/RedPitaya-FPGA/prj/Examples/Frequency_counter/tmp/freq/freq.srcs/sources_1/bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ds_buf_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/rinu2/Documents/Kichi@git/RedPitaya-FPGA/prj/Examples/Frequency_counter/tmp/freq/freq.srcs/sources_1/bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ds_buf_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/rinu2/Documents/Kichi@git/RedPitaya-FPGA/prj/Examples/Frequency_counter/tmp/freq/freq.srcs/sources_1/bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
# IP: The module: 'system_util_ds_buf_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rinu2/Documents/Kichi@git/RedPitaya-FPGA/prj/Examples/Frequency_counter/tmp/freq/freq.srcs/sources_1/bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ds_buf_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/rinu2/Documents/Kichi@git/RedPitaya-FPGA/prj/Examples/Frequency_counter/tmp/freq/freq.srcs/sources_1/bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ds_buf_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
