# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/rinu2/Documents/kichi@git/RedPitaya-FPGA/prj/Examples/Frequency_counter/cfg/clocks.xdc

# XDC: C:/Users/rinu2/Documents/kichi@git/RedPitaya-FPGA/prj/Examples/Frequency_counter/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_counter_trig_PORT1_0/system_counter_trig_PORT1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_counter_trig_PORT1_0 || ORIG_REF_NAME==system_counter_trig_PORT1_0} -quiet] -quiet

# IP: bd/system/ip/system_fifo_generator_PORT1_0/system_fifo_generator_PORT1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fifo_generator_PORT1_0 || ORIG_REF_NAME==system_fifo_generator_PORT1_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_fifo_PORT1_0/system_xlslice_fifo_PORT1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_fifo_PORT1_0 || ORIG_REF_NAME==system_xlslice_fifo_PORT1_0} -quiet] -quiet

# IP: bd/system/ip/system_counter_trig_PORT2_0/system_counter_trig_PORT2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_counter_trig_PORT2_0 || ORIG_REF_NAME==system_counter_trig_PORT2_0} -quiet] -quiet

# IP: bd/system/ip/system_fifo_generator_PORT2_0/system_fifo_generator_PORT2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fifo_generator_PORT2_0 || ORIG_REF_NAME==system_fifo_generator_PORT2_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_fifo_PORT2_0/system_xlslice_fifo_PORT2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_fifo_PORT2_0 || ORIG_REF_NAME==system_xlslice_fifo_PORT2_0} -quiet] -quiet

# IP: bd/system/ip/system_GPIO_change_0_0/system_GPIO_change_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_GPIO_change_0_0 || ORIG_REF_NAME==system_GPIO_change_0_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_125M_0 || ORIG_REF_NAME==system_rst_ps7_0_125M_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_adc_0_0/system_axis_red_pitaya_adc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_adc_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_0_0/system_signal_split_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_signal_split_0_0 || ORIG_REF_NAME==system_signal_split_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_dac_0_0/system_axis_red_pitaya_dac_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_dac_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_dac_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_combine_0_0/system_signal_combine_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_signal_combine_0_0 || ORIG_REF_NAME==system_signal_combine_0_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ds_buf_1_0 || ORIG_REF_NAME==system_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ds_buf_2_0 || ORIG_REF_NAME==system_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/system/ip/system_floating_point_0_0/system_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_floating_point_0_0 || ORIG_REF_NAME==system_floating_point_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_constant_0_1/system_axis_constant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_constant_0_1 || ORIG_REF_NAME==system_axis_constant_0_1} -quiet] -quiet

# IP: bd/system/ip/system_int_to_float_axi_0_0/system_int_to_float_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_int_to_float_axi_0_0 || ORIG_REF_NAME==system_int_to_float_axi_0_0} -quiet] -quiet

# IP: bd/system/ip/system_float_to_int_axi_0_1/system_float_to_int_axi_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_float_to_int_axi_0_1 || ORIG_REF_NAME==system_float_to_int_axi_0_1} -quiet] -quiet

# IP: bd/system/ip/system_adder_axi_0_0/system_adder_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_adder_axi_0_0 || ORIG_REF_NAME==system_adder_axi_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_1/system_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_1 || ORIG_REF_NAME==system_xlconstant_0_1} -quiet] -quiet

# IP: bd/system/ip/system_adder_axi_0_1/system_adder_axi_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_adder_axi_0_1 || ORIG_REF_NAME==system_adder_axi_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axis_constant_1_3/system_axis_constant_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_constant_1_3 || ORIG_REF_NAME==system_axis_constant_1_3} -quiet] -quiet

# IP: bd/system/ip/system_floating_point_0_4/system_floating_point_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_floating_point_0_4 || ORIG_REF_NAME==system_floating_point_0_4} -quiet] -quiet

# IP: bd/system/ip/system_float_to_int_axi_0_5/system_float_to_int_axi_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_float_to_int_axi_0_5 || ORIG_REF_NAME==system_float_to_int_axi_0_5} -quiet] -quiet

# IP: bd/system/ip/system_int_to_float_axi_0_4/system_int_to_float_axi_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_int_to_float_axi_0_4 || ORIG_REF_NAME==system_int_to_float_axi_0_4} -quiet] -quiet

# IP: bd/system/ip/system_axis_constant_1_4/system_axis_constant_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_constant_1_4 || ORIG_REF_NAME==system_axis_constant_1_4} -quiet] -quiet

# IP: bd/system/ip/system_floating_point_0_5/system_floating_point_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_floating_point_0_5 || ORIG_REF_NAME==system_floating_point_0_5} -quiet] -quiet

# IP: bd/system/ip/system_float_to_int_axi_0_6/system_float_to_int_axi_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_float_to_int_axi_0_6 || ORIG_REF_NAME==system_float_to_int_axi_0_6} -quiet] -quiet

# IP: bd/system/ip/system_int_to_float_axi_0_5/system_int_to_float_axi_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_int_to_float_axi_0_5 || ORIG_REF_NAME==system_int_to_float_axi_0_5} -quiet] -quiet

# IP: bd/system/ip/system_axis_constant_1_5/system_axis_constant_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_constant_1_5 || ORIG_REF_NAME==system_axis_constant_1_5} -quiet] -quiet

# IP: bd/system/ip/system_floating_point_0_6/system_floating_point_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_floating_point_0_6 || ORIG_REF_NAME==system_floating_point_0_6} -quiet] -quiet

# IP: bd/system/ip/system_float_to_int_axi_0_7/system_float_to_int_axi_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_float_to_int_axi_0_7 || ORIG_REF_NAME==system_float_to_int_axi_0_7} -quiet] -quiet

# IP: bd/system/ip/system_int_to_float_axi_0_6/system_int_to_float_axi_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_int_to_float_axi_0_6 || ORIG_REF_NAME==system_int_to_float_axi_0_6} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_1_4/system_axi_gpio_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_4 || ORIG_REF_NAME==system_axi_gpio_1_4} -quiet] -quiet

# IP: bd/system/ip/system_s00_data_fifo_0/system_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_data_fifo_0 || ORIG_REF_NAME==system_s00_data_fifo_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
